### ISSUE TITLE
Gradients do not bleed into each other

### ISSUE THREAD

**Issue by davetao** [dynamitechetan/Flowing-Gradient#4]
Hi.

I was wondering if the library was design to bleed the gradients between each other. At the moment, there doesn't appear to be any transition other than jumping between each other

**Comment by dynamitechetan** [comment]
ok. this issue comes when you have defined a different animation duration in your xml and java.
 `xml   <item android:drawable="@drawable/one" android:duration="4000"  />`
android:duration and          gradient:transition_duration = "4000" or in java                 .setTransitionDuration(4000) ... it should be same... not exactly 4000 ... but any other value...

if you are not using your own gradients then you should use duration as 4000.... if you want to change this speed ... you have to define your own gradients with your android:duration value. 
If everything is correct then gradients do bleed into each other.

**Comment by davetao** [comment]
Oh that makes sense. thank you !
